version: "3.8"

services:
  postgres:
    build:
      context: ./docker_compose/postgres/
    image: app-postgres
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    expose:
      - "5432"
  elasticsearch:
    build:
      context: ./docker_compose/elasticsearch/
    image: app-es
    expose:
      - "9201"
      - "9300"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    volumes:
      - "./conf/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml"
      - "./conf/log4j2.properties:/usr/share/elasticsearch/config/log4j2.properties"
      - "./conf/jvm.options:/usr/share/elasticsearch/config/jvm.options"
    depends_on:
      - postgres
  loader:
    build:
      context: .
      dockerfile: ./docker_compose/pyramid/Dockerfile
    image: app-pyramid
    command: python src/encoded/devs.py development.ini --app-name app --init --load
    depends_on:
      - postgres
      - elasticsearch
  pyramid:
    build:
      context: .
      dockerfile: ./docker_compose/pyramid/Dockerfile
    image: app-pyramid
    command: pserve development.ini
    ports:
      - "6543:6543"
    profiles:
      - serving
  nginx:
    image: nginx:1.21.4
    volumes:
      - "./nginx-dev.conf:/etc/nginx/nginx.conf:delegated"
    command: nginx -c /etc/nginx/nginx.conf -g 'daemon off; pid /dev/null;'
    ports:
      - "8000:8000"
    profiles:
      - proxying