#cloud-config
ssh_authorized_keys:
  - %(LOCAL_SSH_KEY)s
apt_sources:
- source: "deb https://artifacts.elastic.co/packages/5.x/apt stable main"
- source: "deb http://apt.postgresql.org/pub/repos/apt/ bionic-pgdg main"
bootcmd:
- set -ex
- cloud-init-per once apt-update apt-get update
- cloud-init-per once fallocate-swapfile fallocate -l 4G /swapfile
- cloud-init-per once chmod-swapfile chmod 600 /swapfile
- cloud-init-per once mkswap-swapfile mkswap /swapfile
- cloud-init-per once curl-nodeinstall curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash -
- cloud-init-per once aptkeyget-elasticsearch wget -qO - https://artifacts.elastic.co/GPG-KEY-elasticsearch > /etc/apt/es_gpg_key
- cloud-init-per once aptkeyadd-elasticsearch apt-key add /etc/apt/es_gpg_key
- cloud-init-per once aptkeyget-postgres wget -qO - https://www.postgresql.org/media/keys/ACCC4CF8.asc > /etc/apt/pg_gpg_key
- cloud-init-per once aptkeyadd-postgres apt-key add /etc/apt/pg_gpg_key
packages:
- awscli
- git
- unattended-upgrades
# apache
- apache2
- apache2-utils
- ssl-cert
- libapache2-mod-wsgi-py3
# cloudwatchmon
# encoded app install
## ckeditor
- bsdtar
## Pillow
- libjpeg8-dev
- zlib1g-dev
## psycopg2
- libpq-dev
# es
- apt-transport-https
- elasticsearch
# node
- nodejs
## node optional installed for native add-ons
- g++
- gcc
- make
# postgresql
- daemontools
- postgresql-11
# python
- build-essential
- libffi-dev
- libssl-dev
- python3.7-dev
- python3-pip
- python3.7-venv
- software-properties-common
# redis
- redis-server
# wal-e
- lzop
# # unknown - Leaving these here for a bit just in case
# - apache2-mpm-worker
# - graphviz
# - libevent-dev
# - libmagic-dev
# - libxml2-dev
# - libxslt1-dev
# - ntp
# - pv
# - ruby-dev
# - update-notifier-common
# - bsd-mailx
power_state:
  mode: reboot
output:
  all: '| tee -a /var/log/cloud-init-output.log'
runcmd:
- cloud-init-per once encd-git-repo sudo -u ubuntu git clone %(GIT_REPO)s /home/ubuntu/encoded
- cloud-init-per once encd-git-branch sudo -u ubuntu git -C /home/ubuntu/encoded checkout -b ENCD-3983-update-to-ubuntu-18 %(GIT_REMOTE)s/ENCD-3983-update-to-ubuntu-18
- cloud-init-per once encd-post-boot sudo -u ubuntu %(CC_DIR)s/post-boot-install.sh %(S3_AUTH_KEYS)s
- cloud-init-per once encd-java sudo -u ubuntu %(CC_DIR)s/java11-oracle-install.sh
- cloud-init-per once encd-redis %(CC_DIR)s/redis-install.sh %(REDIS_PORT)s
- cloud-init-per once encd-elasticsearch %(CC_DIR)s/es-install.sh NONE %(JVM_GIGS)s %(ES_OPT_FILENAME)s NONE NONE
- cloud-init-per once encd-cloudwatch %(CC_DIR)s/cloudwatchmon-install.sh
- cloud-init-per always encd-post-ami %(CC_DIR)s/post-ami-install.sh %(CC_DIR)s %(ROLE)s %(WALE_S3_PREFIX)s %(PG_VERSION)s %(GIT_REPO)s %(GIT_REMOTE)s %(GIT_BRANCH)s %(ES_IP)s %(ES_PORT)s %(REGION_INDEX)s %(APP_WORKERS)s %(BATCHUPGRADE_VARS)s
users:
- default
- name: build
  gecos: Build user
  inactive: true
  system: true
  shell: /bin/bash
- name: encoded
  gecos: ENCODE Metadata Database daemon user
  inactive: true
  system: true
  homedir: /srv/encoded
  shell: /bin/bash
write_files:
- path: /etc/apt/apt.conf.d/20auto-upgrades
  content: |
    APT::Periodic::Update-Package-Lists "1";
    APT::Periodic::Unattended-Upgrade "1";
- path: /etc/apt/apt.conf.d/50unattended-upgrades
  content: |
    Unattended-Upgrade::Allowed-Origins {
        "${distro_id} ${distro_codename}-security";
    };
    Unattended-Upgrade::Mail "encode-devops@lists.stanford.edu";
    Unattended-Upgrade::Automatic-Reboot "false";
- path: /etc/cron.d/cloudwatchmon
  content: |
    */5 * * * * nobody /opt/cloudwatchmon/bin/mon-put-instance-stats.py --mem-util --swap-util --disk-space-util --disk-path=/ --from-cron
