#!/bin/bash
while :
    do
        now=$(date +"%Y%m%d%H%M%S")
        /opt/encoded/checkfiles/bin/python /opt/encoded/checkfiles/checkfiles.py "$@" --out $now-checkfiles.log --err $now-checkfiles-error.log --include-unexpired-upload 2> $now-errors.log 1> $now-output.log
        sleep 480m
done