#!/bin/bash
while :
    do
        now=$(date +"%Y%m%d%H%M%S")
        /opt/encoded/checkfiles/bin/python /opt/encoded/checkfiles/checkfiles.py --username $2 --password $4 --bot-tocken $6 $7 --out $now-checkfiles.log --err $now-checkfiles-error.log --include-unexpired-upload 2> $now-errors.log 1> $now-output.log
        sleep 480m
done