"""Add rid index to propsheets

Revision ID: cfcf1fdff25c
Revises: 
Create Date: 2018-01-31 19:24:54.916281

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cfcf1fdff25c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_propsheets_rid'), 'propsheets', ['rid'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_propsheets_rid'), table_name='propsheets')
    # ### end Alembic commands ###
