# Note this also shows the final datastructure for ontology.json
ntr_assays = {
    "NTR:0000612": {
        "assay": ['RNA binding'],
        "category": [],
        "developmental": [],
        "name": "Switchgear",
        "objectives": [],
        "organs": [],
        "preferred_name": "",
        "slims": [],
        "synonyms": [],
        "systems": [],
        "types": []
    },
    "NTR:0000762": {
        "assay": ['Transcription'],
        "category": [],
        "developmental": [],
        "name": "shRNA knockdown followed by RNA-seq",
        "objectives": [],
        "organs": [],
        "preferred_name": "shRNA RNA-seq",
        "slims": [],
        "synonyms": [],
        "systems": [],
        "types": []
    },
    "NTR:0000763": {
        "assay": ['Transcription'],
        "category": [],
        "developmental": [],
        "name": "siRNA knockdown followed by RNA-seq",
        "objectives": [],
        "organs": [],
        "preferred_name": "siRNA RNA-seq",
        "slims": [],
        "synonyms": [],
        "systems": [],
        "types": []
    },
    "NTR:0001132": {
        "assay": ['RNA binding'],
        "category": [],
        "developmental": [],
        "name": "RNA Bind-N-Seq",
        "objectives": [],
        "organs": [],
        "preferred_name": "RNA Bind-N-Seq",
        "slims": [],
        "synonyms": [],
        "systems": [],
        "types": []
    },
    "NTR:0004774": {
        "assay": ['DNA accessibility'],
        "category": [],
        "developmental": [],
        "name": "genetic modification followed by DNase-seq",
        "objectives": [],
        "organs": [],
        "preferred_name": "GM DNase-seq",
        "slims": [],
        "synonyms": [],
        "systems": [],
        "types": []
    },
    "NTR:0003814": {
        "assay": ['Transcription'],
        "category": [],
        "developmental": [],
        "name": "CRISPR genome editing followed by RNA-seq",
        "objectives": [],
        "organs": [],
        "preferred_name": "CRISPR RNA-seq",
        "slims": [],
        "synonyms": [],
        "systems": [],
        "types": []
    },
    "NTR:0004619": {
        "assay": ['Transcription'],
        "category": [],
        "developmental": [],
        "name": "CRISPRi followed by RNA-seq",
        "objectives": [],
        "organs": [],
        "preferred_name": "CRISPRi RNA-seq",
        "slims": [],
        "synonyms": [],
        "systems": [],
        "types": []
    },
    "NTR:0000438": {
        "assay": ['DNA accessibility'],
        "category": [],
        "developmental": [],
        "name": "single-nucleus ATAC-seq",
        "objectives": [],
        "organs": [],
        "preferred_name": "snATAC-seq",
        "slims": [],
        "synonyms": [],
        "systems": [],
        "types": []
    },
    "NTR:0000433": {
        "assay": ['RNA structure'],
        "category": [],
        "developmental": [],
        "name": "in vivo click selective 2-hydroxyl acylation and profiling experiment",
        "objectives": [],
        "organs": [],
        "preferred_name": "icSHAPE",
        "slims": [],
        "synonyms": [],
        "systems": [],
        "types": []
    },
    "NTR:0000444": {
        "assay": ['DNA accessibility'],
        "category": [],
        "developmental": [],
        "name": "single-cell ATAC-seq",
        "objectives": [],
        "organs": [],
        "preferred_name": "scATAC-seq",
        "slims": [],
        "synonyms": [],
        "systems": [],
        "types": []
    },
    "NTR:0000445": {
        "assay": ['Transcription'],
        "category": [],
        "developmental": [],
        "name": "long read RNA sequencing",
        "objectives": [],
        "organs": [],
        "preferred_name": "long read RNA-seq",
        "slims": [],
        "synonyms": [],
        "systems": [],
        "types": []
    },
    "NTR:0000458": {
        "assay": ['DNA sequencing'],
        "category": [],
        "developmental": [],
        "name": "Clone-seq",
        "objectives": [],
        "organs": [],
        "preferred_name": "Clone-seq",
        "slims": [],
        "synonyms": [],
        "systems": [],
        "types": []
    },
    "NTR:0000513": {
        "assay": ['3D chromatin structure'],
        "category": [],
        "developmental": [],
        "name": "proximity ligation-assisted ChIP-seq",
        "objectives": [],
        "organs": [],
        "preferred_name": "PLAC-seq",
        "slims": [],
        "synonyms": [],
        "systems": [],
        "types": []
    },
    "NTR:0000519": {
        "assay": ['Functional characterization'],
        "category": [],
        "developmental": [],
        "name": "pooled clone sequencing",
        "objectives": [],
        "organs": [],
        "preferred_name": "pooled clone sequencing",
        "slims": [],
        "synonyms": [],
        "systems": [],
        "types": []
    },
    "NTR:0000520": {
        "assay": ['Functional characterization'],
        "category": [],
        "developmental": [],
        "name": "CRISPR screen",
        "objectives": [],
        "organs": [],
        "preferred_name": "CRISPR screen",
        "slims": [],
        "synonyms": [],
        "systems": [],
        "types": []
    },
    "NTR:0000536": {
        "assay": ['Transcription'],
        "category": [],
        "developmental": [],
        "name": "PRO-cap",
        "objectives": [],
        "organs": [],
        "preferred_name": "PRO-cap",
        "slims": [],
        "synonyms": [],
        "systems": [],
        "types": []
    },
    "NTR:0000538": {
        "assay": ['RNA structure'],
        "category": [],
        "developmental": [],
        "name": "in vivo click light activated structural examination of RNA",
        "objectives": [],
        "organs": [],
        "preferred_name": "icLASER",
        "slims": [],
        "synonyms": [],
        "systems": [],
        "types": []
    },
        "NTR:0000544": {
        "assay": ['3D chromatin structure'],
        "category": [],
        "developmental": [],
        "name": "split-pool recognition of interactions by tag extension",
        "objectives": [],
        "organs": [],
        "preferred_name": "SPRITE",
        "slims": [],
        "synonyms": [],
        "systems": [],
        "types": []
    },
        "NTR:0000551": {
        "assay": ['Functional characterization'],
        "category": [],
        "developmental": [],
        "name": "transgenic enhancer assay",
        "objectives": [],
        "organs": [],
        "preferred_name": "",
        "slims": [],
        "synonyms": [],
        "systems": [],
        "types": []
    },
    "NTR:0000557": {
        "assay": ['DNA binding'],
        "category": [],
        "developmental": [],
        "name": "Cleavage Under Targets and Release Using Nuclease",
        "objectives": [],
        "organs": [],
        "preferred_name": "CUT&RUN",
        "slims": [],
        "synonyms": [],
        "systems": [],
        "types": []
    },
    "NTR:0000562": {
        "assay": ['3D chromatin structure'],
        "category": [],
        "developmental": [],
        "name": "split-pool recognition of interactions by tag extension with immunoprecipitation",
        "objectives": [],
        "organs": [],
        "preferred_name": "SPRITE-IP",
        "slims": [],
        "synonyms": [],
        "systems": [],
        "types": []
    },
}

ntr_biosamples = {
     "NTR:0000491": {
        "category": [],
        "cells": [],
        "developmental": ["mesoderm"],
        "name": "Right ventricle myocardium inferior",
        "objectives": [],
        "organs": ["heart"],
        "preferred_name": "",
        "slims": [],
        "synonyms": [],
        "systems": ["circulatory system"],
        "types": []
    },
    "NTR:0000492": {
        "category": [],
        "cells": [],
        "developmental": ["mesoderm"],
        "name": "Right ventricle myocardium superior",
        "objectives": [],
        "organs": ["heart"],
        "preferred_name": "",
        "slims": [],
        "synonyms": [],
        "systems": ["circulatory system"],
        "types": []
    },
    "NTR:0000493": {
        "category": [],
        "cells": [],
        "developmental": ["mesoderm"],
        "name": "left ventricle myocardium inferior",
        "objectives": [],
        "organs": ["heart"],
        "preferred_name": "",
        "slims": [],
        "synonyms": [],
        "systems": ["circulatory system"],
        "types": []
    },
    "NTR:0000494": {
        "category": [],
        "cells": [],
        "developmental": ["mesoderm"],
        "name": "left ventricle myocardium superior",
        "objectives": [],
        "organs": ["heart"],
        "preferred_name": "",
        "slims": [],
        "synonyms": [],
        "systems": ["circulatory system"],
        "types": []
    },
    "NTR:0000528": {
        "category": [],
        "cells": [],
        "developmental": ["mesoderm"],
        "name": "left arm bone",
        "objectives": [],
        "organs": ["bone element", "skeleton", "limb"],
        "preferred_name": "",
        "slims": [],
        "synonyms": [],
        "systems": ["skeletal system"],
        "types": []
    },
    "NTR:0000529": {
        "category": [],
        "cells": [],
        "developmental": ["mesoderm"],
        "name": "right arm bone",
        "objectives": [],
        "organs": ["bone element", "skeleton", "limb"],
        "preferred_name": "",
        "slims": [],
        "synonyms": [],
        "systems": ["skeletal system"],
        "types": []
    },
    "NTR:0000530": {
        "category": [],
        "cells": [],
        "developmental": ["mesoderm"],
        "name": "left leg bone",
        "objectives": [],
        "organs": ["bone element", "skeleton", "limb"],
        "preferred_name": "",
        "slims": [],
        "synonyms": [],
        "systems": ["skeletal system"],
        "types": []
    },
    "NTR:0000531": {
        "category": [],
        "cells": [],
        "developmental": ["mesoderm"],
        "name": "right leg bone",
        "objectives": [],
        "organs": ["bone element", "skeleton", "limb"],
        "preferred_name": "",
        "slims": [],
        "synonyms": [],
        "systems": ["skeletal system"],
        "types": []
    },
    "NTR:0001226": {
        "category": [],
        "cells": [],
        "developmental": ["endoderm"],
        "name": "parathyroid adenoma",
        "objectives": [],
        "organs": ["paraythroid gland"],
        "preferred_name": "",
        "slims": [],
        "synonyms": [],
        "systems": ["endocrine system"],
        "types": []
    },
    "NTR:0001407": {
        "category": [],
        "cells": [],
        "developmental": ["ectoderm"],
        "name": "germinal matrix",
        "objectives": [],
        "organs": ["brain"],
        "preferred_name": "",
        "slims": [],
        "synonyms": [],
        "systems": ["central nervous system"],
        "types": []
    },
    "NTR:0002929": {
        "category": [],
        "cells": [],
        "developmental": ["endoderm"],
        "name": "posterior foregut",
        "objectives": [],
        "organs": [],
        "preferred_name": "",
        "slims": [],
        "synonyms": [],
        "systems": ["digestive system"],
        "types": []
    },
    "NTR:0003013": {
        "category": [],
        "cells": [],
        "developmental": ["mesoderm"],
        "name": "placental basal plate",
        "objectives": [],
        "organs": ["extraembryonic component", "placenta"],
        "preferred_name": "",
        "slims": [],
        "synonyms": [],
        "systems": ["reproductive system"],
        "types": []
    },
    "NTR:0005063": {
        "category": [],
        "cells": ["stem cell"],
        "developmental": [],
        "name": "dedifferentiated amniotic fluid mesenchymal stem cell",
        "objectives": [],
        "organs": ["connective tissue", "extraembryonic component"],
        "preferred_name": "",
        "slims": [],
        "synonyms": [],
        "systems": [],
        "types": []
    },
    "NTR:0004218": {
        "category": [],
        "cells": ["hematopoietic cell", "leukocyte", "T cell"],
        "developmental": [],
        "name": "inflammation-experienced regulatory T-cells",
        "objectives": [],
        "organs": ["blood", "bodily fluid"],
        "preferred_name": "",
        "slims": [],
        "synonyms": [],
        "systems": ["immune system"],
        "types": []
    },
    "NTR:0004148": {
        "category": [],
        "cells": ["hematopoietic cell", "leukocyte", "T cell"],
        "developmental": [],
        "name": "activated regulatory T-cells",
        "objectives": [],
        "organs": ["blood", "bodily fluid"],
        "preferred_name": "",
        "slims": [],
        "synonyms": [],
        "systems": ["immune system"],
        "types": []
    },
    "NTR:0003079": {
        "category": [],
        "cells": ["fibroblast"],
        "developmental": [],
        "name": "fibroblast of breast",
        "objectives": [],
        "organs": ["breast"],
        "preferred_name": "",
        "slims": [],
        "synonyms": [],
        "systems": [],
        "types": []
    },
    "NTR:0001801": {
        "category": [],
        "cells": ["neural cell", "retinal cell"],
        "developmental": ["ectoderm"],
        "name": "retinal alpha ganglion cell",
        "objectives": [],
        "organs": [ "eye" ],
        "preferred_name": "",
        "slims": [],
        "synonyms": [],
        "systems": ["sensory system", "central nervous system"],
        "types": []
    },
    "NTR:0000741": {
        "category": [],
        "cells": ["hematopoietic cell", "leukocyte", "B cell"],
        "developmental": [],
        "name": "splenic B cell",
        "objectives": [],
        "organs": ["spleen", "blood", "bodily fluid"],
        "preferred_name": "",
        "slims": [],
        "synonyms": [],
        "systems": ["immune system"],
        "types": []
    },
    "NTR:0000722": {
        "category": [],
        "cells": ["hematopoietic cell", "myeloid cell", "progenitor cell"],
        "developmental": [],
        "name": "c-Kit-positive CD71-positive TER-119-positive erythroid progenitor cells",
        "objectives": [],
        "organs": [],
        "preferred_name": "",
        "slims": [],
        "synonyms": [],
        "systems": [],
        "types": []
    },
    "NTR:0000721": {
        "category": [],
        "cells": ["hematopoietic cell", "myeloid cell", "progenitor cell"],
        "developmental": [],
        "name": "c-Kit-positive CD71-positive TER-119-negative erythroid progenitor cells",
        "objectives": [],
        "organs": [],
        "preferred_name": "",
        "slims": [],
        "synonyms": [],
        "systems": [],
        "types": []
    },
    "NTR:0000720": {
        "category": [],
        "cells": ["hematopoietic cell", "myeloid cell", "progenitor cell"],
        "developmental": [],
        "name": "c-Kit-positive CD71-negative TER-119-negative erythroid progenitor cells",
        "objectives": [],
        "organs": [],
        "preferred_name": "",
        "slims": [],
        "synonyms": [],
        "systems": [],
        "types": []
    },
    "NTR:0000719": {
        "category": [],
        "cells": ["hematopoietic cell", "myeloid cell", "progenitor cell"],
        "developmental": [],
        "name": "c-Kit-negative CD71-positive TER-119-positive erythroid progenitor cells",
        "objectives": [],
        "organs": [],
        "preferred_name": "",
        "slims": [],
        "synonyms": [],
        "systems": [],
        "types": []
    },
    "NTR:0000714": {
        "category": [],
        "cells": ["stem cell"],
        "developmental": [],
        "name": "leukemia stem cell",
        "objectives": [],
        "organs": [],
        "preferred_name": "",
        "slims": [],
        "synonyms": [],
        "systems": [],
        "types": []
    },
    "NTR:0000537": {
        "category": [],
        "cells": ["hematopoietic cell", "leukocyte", "T cell"],
        "developmental": [],
        "name": "activated T-cell",
        "objectives": [],
        "organs": ["blood", "bodily fluid"],
        "preferred_name": "",
        "slims": [],
        "synonyms": [],
        "systems": ["immune system"],
        "types": []
    },
    "NTR:0000535": {
        "category": [],
        "cells": ["hematopoietic cell", "leukocyte"],
        "developmental": [],
        "name": "CD14-negative NK cell",
        "objectives": [],
        "organs": ["blood", "bodily fluid"],
        "preferred_name": "",
        "slims": [],
        "synonyms": [],
        "systems": ["immune system"],
        "types": []
    },
    "NTR:0000527": {
        "category": [],
        "cells": ["fibroblast"],
        "developmental": ["ectoderm"],
        "name": "fibroblast of skin of back",
        "objectives": [],
        "organs": ["skin of body"],
        "preferred_name": "",
        "slims": [],
        "synonyms": [],
        "systems": ["integumental system"],
        "types": []
    },
    "NTR:0000526": {
        "category": [],
        "cells": ["fibroblast"],
        "developmental": ["ectoderm"],
        "name": "fibroblast of skin of upper back",
        "objectives": [],
        "organs": ["skin of body"],
        "preferred_name": "",
        "slims": [],
        "synonyms": [],
        "systems": ["integumental system"],
        "types": []
    },
    "NTR:0000525": {
        "category": [],
        "cells": ["fibroblast"],
        "developmental": ["ectoderm"],
        "name": "fibroblast of skin of right biceps",
        "objectives": [],
        "organs": ["skin of body"],
        "preferred_name": "",
        "slims": [],
        "synonyms": [],
        "systems": ["integumental system"],
        "types": []
    },
    "NTR:0000524": {
        "category": [],
        "cells": ["fibroblast"],
        "developmental": ["ectoderm"],
        "name": "fibroblast of skin of scalp",
        "objectives": [],
        "organs": ["skin of body"],
        "preferred_name": "",
        "slims": [],
        "synonyms": [],
        "systems": ["integumental system"],
        "types": []
    },
    "NTR:0000523": {
        "category": [],
        "cells": ["fibroblast"],
        "developmental": ["ectoderm"],
        "name": "fibroblast of skin of right quadriceps",
        "objectives": [],
        "organs": ["skin of body"],
        "preferred_name": "",
        "slims": [],
        "synonyms": [],
        "systems": ["integumental system"],
        "types": []
    },
    "NTR:0000522": {
        "category": [],
        "cells": ["fibroblast"],
        "developmental": [ "ectoderm" ],
        "name": "fibroblast of skin of left quadriceps",
        "objectives": [],
        "organs": ["skin of body"],
        "preferred_name": "",
        "slims": [],
        "synonyms": [],
        "systems": ["integumental system"],
        "types": []
    },
    "NTR:0000521": {
        "category": [],
        "cells": ["fibroblast"],
        "developmental": ["ectoderm"],
        "name": "fibroblast of skin of left biceps",
        "objectives": [],
        "organs": ["skin of body"],
        "preferred_name": "",
        "slims": [],
        "synonyms": [],
        "systems": ["integumental system"],
        "types": []
    },
    "NTR:0000506": {
        "category": [],
        "cells": ["hematopoietic cell", "leukocyte", "B cell"],
        "developmental": [],
        "name": "B cell",
        "objectives": [],
        "organs": ["blood", "bodily fluid"],
        "preferred_name": "",
        "slims": [],
        "synonyms": [],
        "systems": ["immune system"],
        "types": []
    },
    "NTR:0000505": {
        "category": [],
        "cells": ["hematopoietic cell", "leukocyte"],
        "developmental": [],
        "name": "dendritic cell",
        "objectives": [],
        "organs": [],
        "preferred_name": "",
        "slims": [],
        "synonyms": [],
        "systems": ["immune system"],
        "types": []
    },
    "NTR:0000504": {
        "category": [],
        "cells": ["hematopoietic cell", "leukocyte", "T cell"],
        "developmental": [],
        "name": "activated CD8-positive, alpha-beta T cell",
        "objectives": [],
        "organs": ["blood", "bodily fluid"],
        "preferred_name": "",
        "slims": [],
        "synonyms": [],
        "systems": ["immune system"],
        "types": []
    },
    "NTR:0000503": {
        "category": [],
        "cells": ["hematopoietic cell", "leukocyte", "T cell"],
        "developmental": [],
        "name": "CD8-positive, alpha-beta memory T cell",
        "objectives": [],
        "organs": ["blood", "bodily fluid"],
        "preferred_name": "",
        "slims": [],
        "synonyms": [],
        "systems": ["immune system"],
        "types": []
    },
    "NTR:0000502": {
        "category": [],
        "cells": ["hematopoietic cell", "leukocyte", "T cell"],
        "developmental": [],
        "name": "activated CD8-positive, alpha-beta T cell",
        "objectives": [],
        "organs": ["blood", "bodily fluid"],
        "preferred_name": "",
        "slims": [],
        "synonyms": [],
        "systems": ["immune system"],
        "types": []
    },
    "NTR:0000501": {
        "category": [],
        "cells": ["hematopoietic cell", "leukocyte", "T cell"],
        "developmental": [],
        "name": "CD8-positive naive resting alpha-beta T cell",
        "objectives": [],
        "organs": ["blood", "bodily fluid"],
        "preferred_name": "",
        "slims": [],
        "synonyms": [],
        "systems": ["immune system"],
        "types": []
    },
    "NTR:0000500": {
        "category": [],
        "cells": ["hematopoietic cell", "leukocyte", "T cell"],
        "developmental": [],
        "name": "activated CD8-positive, alpha-beta T cell",
        "objectives": [],
        "organs": ["blood", "bodily fluid"],
        "preferred_name": "",
        "slims": [],
        "synonyms": [],
        "systems": ["immune system"],
        "types": []
    },
    "NTR:0000499": {
        "category": [],
        "cells": ["hematopoietic cell", "leukocyte", "T cell"],
        "developmental": [],
        "name": "activated CD4-positive, alpha-beta T cell",
        "objectives": [],
        "organs": ["blood", "bodily fluid"],
        "preferred_name": "",
        "slims": [],
        "synonyms": [],
        "systems": ["immune system"],
        "types": []
    },
    "NTR:0000498": {
        "category": [],
        "cells": ["hematopoietic cell", "leukocyte", "T cell"],
        "developmental": [],
        "name": "CD4-positive, alpha-beta memory T cell",
        "objectives": [],
        "organs": ["blood", "bodily fluid"],
        "preferred_name": "",
        "slims": [],
        "synonyms": [],
        "systems": ["immune system"],
        "types": []
    },
    "NTR:0000497": {
        "category": [],
        "cells": ["hematopoietic cell", "leukocyte", "T cell"],
        "developmental": [],
        "name": "activated CD4-positive, alpha-beta T cell",
        "objectives": [],
        "organs": ["blood", "bodily fluid"],
        "preferred_name": "",
        "slims": [],
        "synonyms": [],
        "systems": ["immune system"],
        "types": []
    },
    "NTR:0000496": {
        "category": [],
        "cells": ["hematopoietic cell", "leukocyte", "T cell"],
        "developmental": [],
        "name": "CD4-positive naive resting alpha-beta T cell",
        "objectives": [],
        "organs": ["blood", "bodily fluid"],
        "preferred_name": "",
        "slims": [],
        "synonyms": [],
        "systems": ["immune system"],
        "types": []
    },
    "NTR:0000495": {
        "category": [],
        "cells": ["hematopoietic cell", "leukocyte", "T cell"],
        "developmental": [],
        "name": "activated CD4-positive, alpha-beta T cell",
        "objectives": [],
        "organs": ["blood", "bodily fluid"],
        "preferred_name": "",
        "slims": [],
        "synonyms": [],
        "systems": ["immune system"],
        "types": []
    },
    "NTR:0000427": {
        "category": [],
        "cells": ["stem cell"],
        "developmental": ["ectoderm"],
        "name": "neurosphere",
        "objectives": [],
        "organs": [],
        "preferred_name": "",
        "slims": [],
        "synonyms": [],
        "systems": ["central nervous system"],
        "types": []
    },
    "NTR:0005192": {
        "category": [],
        "cells": [],
        "developmental": ["endoderm"],
        "name": "primitive gut cell",
        "objectives": [],
        "organs": ["embryo"],
        "preferred_name": "",
        "slims": [],
        "synonyms": [],
        "systems": ["digestive system"],
        "types": []
    },
    "NTR:0005188": {
        "category": [],
        "cells": [],
        "developmental": ["endoderm"],
        "name": "definitive endodermal cell",
        "objectives": [],
        "organs": ["embryo"],
        "preferred_name": "",
        "slims": [],
        "synonyms": [],
        "systems": [],
        "types": []
    },
    "NTR:0003830": {
        "category": [],
        "cells": ["neural cell"],
        "developmental": ["ectoderm"],
        "name": "mid-neurogenesis radial glial cells",
        "objectives": [],
        "organs": [],
        "preferred_name": "",
        "slims": [],
        "synonyms": [],
        "systems": ["central nervous system"],
        "types": []
    },
    "NTR:0001484": {
        "category": [],
        "cells": [],
        "developmental": ["endoderm"],
        "name": "islet precursor cell",
        "objectives": [],
        "organs": ["pancreas"],
        "preferred_name": "",
        "slims": [],
        "synonyms": [],
        "systems": ["endocrine system"],
        "types": []
    },
    "NTR:0000856": {
        "category": [],
        "cells": [],
        "developmental": ["mesoderm", "endoderm"],
        "name": "mesendoderm",
        "objectives": [],
        "organs": ["embryo"],
        "preferred_name": "",
        "slims": [],
        "synonyms": [],
        "systems": [],
        "types": []
    },
    "NTR:0000561": {
        "category": [],
        "cells": [],
        "developmental": ["endoderm"],
        "name": "hepatic endoderm",
        "objectives": [],
        "organs": ["exocrine gland", "liver", "endocrine gland"],
        "preferred_name": "",
        "slims": [],
        "synonyms": [],
        "systems": ["endocrine system", "digestive system"],
        "types": []
    },
    "NTR:0000560": {
        "category": [],
        "cells": ["neural cell"],
        "developmental": ["ectoderm"],
        "name": "bipolar spindle neuron",
        "objectives": [],
        "organs": [],
        "preferred_name": "",
        "slims": [],
        "synonyms": [],
        "systems": ["central nervous system"],
        "types": []
    },
    "NTR:0000533": {
        "category": [],
        "cells": ["epithelial cell"],
        "developmental": ["mesoderm"],
        "name": "epicardium (mesothelium) cells",
        "objectives": [],
        "organs": ["heart", "epithelium"],
        "preferred_name": "",
        "slims": [],
        "synonyms": [],
        "systems": ["circulatory system"],
        "types": []
    },
    "NTR:0000514": {
        "category": [],
        "cells": ["progenitor cell"],
        "developmental": [],
        "name": "cardiovascular progenitor cell",
        "objectives": [],
        "organs": [],
        "preferred_name": "",
        "slims": [],
        "synonyms": [],
        "systems": ["circulatory system"],
        "types": []
    },
    "NTR:0000512": {
        "category": [],
        "cells": ["progenitor cell"],
        "developmental": [],
        "name": "nephron progenitor cell",
        "objectives": [],
        "organs": ["kidney"],
        "preferred_name": "",
        "slims": [],
        "synonyms": [],
        "systems": ["excretory system"],
        "types": []
    },
    "NTR:0000474": {
        "category": [],
        "cells": ["progenitor cell"],
        "developmental": ["ectoderm"],
        "name": "ecto neural progenitor cell",
        "objectives": [],
        "organs": [],
        "preferred_name": "",
        "slims": [],
        "synonyms": [],
        "systems": ["central nervous system"],
        "types": []
    },
    "NTR:0000428": {
        "category": [],
        "cells": ["stem cell"],
        "developmental": [],
        "name": "embryoid body cell",
        "objectives": [],
        "organs": ["embryo"],
        "preferred_name": "",
        "slims": [],
        "synonyms": [],
        "systems": [],
        "types": []
    },
        "NTR:0000553": {
        "category": [],
        "cells": ["hematopoietic cell", "leukocyte", "cancer cell"],
        "developmental": ["mesoderm"],
        "name": "HL-60/S4",
        "objectives": [],
        "organs": ["blood", "bodily fluid"],
        "preferred_name": "",
        "slims": [],
        "synonyms": [],
        "systems": ["immune system"],
        "types": []
    }
}
