ab_states = {
    ("compliant", "compliant"): "characterized to standards",
    ("compliant", "exempt from standards"): "characterized to standards with exemption",
    ("compliant", "in progress"): "partially characterized",
    ("compliant", "not compliant"): "not characterized to standards",
    ("compliant", "not reviewed"): "partially characterized",
    ("compliant", "not submitted for review by lab"): "partially characterized",
    ("compliant", "pending dcc review"): "partially characterized",
    ("compliant", None): "partially characterized",
    ("exempt from standards", "compliant"): "characterized to standards with exemption",
    ("exempt from standards", "exempt from standards"): "characterized to standards with exemption",
    ("exempt from standards", "in progress"): "partially characterized",
    ("exempt from standards", "not compliant"): "not characterized to standards",
    ("exempt from standards", "not reviewed"): "partially characterized",
    ("exempt from standards", "not submitted for review by lab"): "partially characterized",
    ("exempt from standards", "pending dcc review"): "partially characterized",
    ("exempt from standards", None): "partially characterized",
    ("in progress", "compliant"): "partially characterized",
    ("in progress", "exempt from standards"): "partially characterized",
    ("in progress", "in progress"): "awaiting characterization",
    ("in progress", "not compliant"): "not characterized to standards",
    ("in progress", "not reviewed"): "awaiting characterization",
    ("in progress", "not submitted for review by lab"): "not pursued",
    ("in progress", "pending dcc review"): "awaiting characterization",
    ("in progress", None): "awaiting characterization",
    ("not compliant", "compliant"): "not characterized to standards",
    ("not compliant", "exempt from standards"): "not characterized to standards",
    ("not compliant", "in progress"): "not characterized to standards",
    ("not compliant", "not compliant"): "not characterized to standards",
    ("not compliant", "not reviewed"): "not characterized to standards",
    ("not compliant", "not submitted for review by lab"): "not characterized to standards",
    ("not compliant", "pending dcc review"): "not characterized to standards",
    ("not compliant", None): "not characterized to standards",
    ("not reviewed", "compliant"): "partially characterized",
    ("not reviewed", "exempt from standards"): "partially characterized",
    ("not reviewed", "in progress"): "awaiting characterization",
    ("not reviewed", "not compliant"): "not characterized to standards",
    ("not reviewed", "not reviewed"): "awaiting characterization",
    ("not reviewed", "not submitted for review by lab"): "not pursued",
    ("not reviewed", "pending dcc review"): "awaiting characterization",
    ("not reviewed", None): "awaiting characterization",
    ("not submitted for review by lab", "compliant"): "partially characterized",
    ("not submitted for review by lab", "exempt from standards"): "partially characterized",
    ("not submitted for review by lab", "in progress"): "not pursued",
    ("not submitted for review by lab", "not compliant"): "not characterized to standards",
    ("not submitted for review by lab", "not reviewed"): "not pursued",
    ("not submitted for review by lab", "not submitted for review by lab"): "not pursued",
    ("not submitted for review by lab", "pending dcc review"): "not pursued",
    ("not submitted for review by lab", None): "not pursued",
    ("pending dcc review", "compliant"): "partially characterized",
    ("pending dcc review", "exempt from standards"): "partially characterized",
    ("pending dcc review", "in progress"): "awaiting characterization",
    ("pending dcc review", "not compliant"): "not characterized to standards",
    ("pending dcc review", "not reviewed"): "awaiting characterization",
    ("pending dcc review", "not submitted for review by lab"): "not pursued",
    ("pending dcc review", "pending dcc review"): "awaiting characterization",
    ("pending dcc review", None): "awaiting characterization",
    (None, "compliant"): "partially characterized",
    (None, "exempt from standards"): "partially characterized",
    (None, "in progress"): "awaiting characterization",
    (None, "not compliant"): "not characterized to standards",
    (None, "not reviewed"): "awaiting characterization",
    (None, "not submitted for review by lab"): "not pursued",
    (None, "pending dcc review"): "awaiting characterization",
    (None, None): "awaiting characterization"
}

ab_state_details = {
    ("compliant", "compliant"): "Fully characterized.",
    ("compliant", "exempt from standards"): "Fully characterized with exemption.",
    ("compliant", "in progress"): "Awaiting a compliant secondary characterization.",
    ("compliant", "not compliant"): "Awaiting a compliant secondary characterization.",
    ("compliant", "not reviewed"): "Secondary characterization not reviewed.",
    ("compliant", "not submitted for review by lab"): "Awaiting a compliant secondary characterization.",
    ("compliant", "pending dcc review"): "Pending review of a secondary characterization.",
    ("compliant", None): "Awaiting submission of a compliant secondary characterization.",
    ("exempt from standards", "compliant"): "Fully characterized with exemption.",
    ("exempt from standards", "exempt from standards"): "Fully characterized with exemption.",
    ("exempt from standards", "in progress"): "Awaiting a compliant secondary characterization.",
    ("exempt from standards", "not compliant"): "Awaiting a compliant secondary characterization.",
    ("exempt from standards", "not reviewed"): "Secondary characterization not reviewed.",
    ("exempt from standards", "not submitted for review by lab"): "Awaiting a compliant secondary characterization.",
    ("exempt from standards", "pending dcc review"): "Pending review of a secondary characterization.",
    ("exempt from standards", None): "Awaiting submission of a compliant secondary characterization.",
    ("in progress", "compliant"): "Awaiting a compliant primary characterization.",
    ("in progress", "exempt from standards"): "Awaiting a compliant primary characterization.",
    ("in progress", "in progress"): "Awaiting compliant primary and secondary characterizations.",
    ("in progress", "not compliant"): "Awaiting compliant primary and secondary characterizations.",
    ("in progress", "not reviewed"): "Awaiting a compliant primary and secondary characterization not reviewed.",
    ("in progress", "not submitted for review by lab"): "Awaiting compliant primary and secondary characterizations.",
    ("in progress", "pending dcc review"): "Awaiting a compliant primary and pending review of a secondary characterization.",
    ("in progress", None): "Awaiting a compliant primary and submission of a secondary characterization.",
    ("not compliant", "compliant"): "Awaiting a compliant primary characterization.",
    ("not compliant", "exempt from standards"): "Awaiting a compliant primary characterization.",
    ("not compliant", "in progress"): "Awaiting compliant primary and secondary characterizations.",
    ("not compliant", "not compliant"): "Awaiting compliant primary and secondary characterizations.",
    ("not compliant", "not reviewed"): "Awaiting a compliant primary and secondary characterization not reviewed.",
    ("not compliant", "not submitted for review by lab"): "Awaiting compliant primary and secondary characterizations.",
    ("not compliant", "pending dcc review"): "Awaiting a compliant primary and pending review of a secondary characterization.",
    ("not compliant", None): "Awaiting a compliant primary and submission of a secondary characterization.",
    ("not reviewed", "compliant"): "Primary characterization not reviewed.",
    ("not reviewed", "exempt from standards"): "Primary characterization not reviewed.",
    ("not reviewed", "in progress"): "Primary characterization not reviewed and awaiting a compliant secondary characterization.",
    ("not reviewed", "not compliant"): "Primary characterization not reviewed and awaiting a compliant secondary characterization.",
    ("not reviewed", "not reviewed"): "Primary and secondary characterizations not reviewed.",
    ("not reviewed", "not submitted for review by lab"): "Primary characterization not reviewed and awaiting a compliant secondary characterization.",
    ("not reviewed", "pending dcc review"): "Primary characterization not reviewed and pending review of a secondary characterization.",
    ("not reviewed", None): "Primary characterization not reviewed and awaiting submission of a secondary characterization.",
    ("not submitted for review by lab", "compliant"): "Awaiting a compliant primary characterization.",
    ("not submitted for review by lab", "exempt from standards"): "Awaiting a compliant primary characterization.",
    ("not submitted for review by lab", "in progress"): "Awaiting compliant primary and secondary characterizations.",
    ("not submitted for review by lab", "not compliant"): "Awaiting compliant primary and secondary characterizations.",
    ("not submitted for review by lab", "not reviewed"): "Awaiting a compliant primary and secondary characterization not reviewed.",
    ("not submitted for review by lab", "not submitted for review by lab"): "Awaiting compliant primary and secondary characterizations.",
    ("not submitted for review by lab", "pending dcc review"): "Awaiting a compliant primary and pending review of a secondary characterization.",
    ("not submitted for review by lab", None): "Awaiting a compliant primary and submission of a secondary characterization.",
    ("pending dcc review", "compliant"): "Pending review of primary characterization.",
    ("pending dcc review", "exempt from standards"): "Pending review of primary characterization.",
    ("pending dcc review", "in progress"): "Pending review of primary characterization and awaiting a compliant secondary characterization.",
    ("pending dcc review", "not compliant"): "Pending review of primary characterization and awaiting a compliant secondary characterization.",
    ("pending dcc review", "not reviewed"): "Pending review of primary characterization and secondary characterization not reviewed.",
    ("pending dcc review", "not submitted for review by lab"): "Pending review of primary characterization and awaiting a compliant secondary characterization.",
    ("pending dcc review", "pending dcc review"): "Pending review of primary and secondary characterizations.",
    ("pending dcc review", None): "Pending review of primary characterization and awaiting submission of a secondary characterization.",
    (None, "compliant"): "Awaiting submission of a primary characterization.",
    (None, "exempt from standards"): "Awaiting submission of a primary characterization.",
    (None, "in progress"): "Awaiting submission of a primary characterization and a compliant secondary characterization.",
    (None, "not compliant"): "Awaiting submission of a primary characterization and a compliant secondary characterization.",
    (None, "not reviewed"): "Awaiting submission of a primary characterization and secondary characterization not reviewed.",
    (None, "not submitted for review by lab"): "Awaiting submission of a primary characterization and a compliant secondary characterization.",
    (None, "pending dcc review"): "Awaiting submission of a primary characterization and pending review of a secondary characterization.",
    (None, None): "Awaiting submission of primary and secondary characterizations."
}