histology_filters = {
    'Acquired cystic disease-associated renal cell carcinoma': 'ACD-RCC',
    'Angiomyolipoma': 'AML',
    'Chromophobe renal cell carcinoma': 'ChRCC',
    'Chromophobe renal cell carcinoma, hybrid type': 'ChRCC',
    'Chromophobe renal cell carcinoma, classic': 'ChRCC',
    'Chromophobe renal cell carcinoma, eosinophilic': 'ChRCC',
    'Clear cell papillary renal cell carcinoma': 'ccPRCC',
    'Clear cell renal cell carcinoma': 'ccRCC',
    'Collecting duct carcinoma': 'CDC',
    'Cystic nephroma': 'CN',
    'Hereditary leiomyomatosis and RCC-associated RCC': 'FH RCC',
    'Metanephric adenoma': 'MA',
    'MiT family translocation renal cell carcinoma': 'MiT TRCC',
    'Mucinous tubular and spindle cell carcinoma': 'MTSCC',
    'Multilocular cystic renal neoplasm of low malignant potential': 'MCRN',
    'Oncocytic renal neoplasm, not further classified': 'RON',
    'Oncocytic renal neoplasm, favor RO': 'RON',
    'Oncocytic renal neoplasm, favor ChRCC': 'RON',
    'Oncocytoma': 'RO',
    'Poorly differentiated malignancy': 'Other',
    'Sarcomatoid, NOS': 'Other',
    'Papillary renal cell carcinoma': 'PRCC',
    'Papillary renal cell carcinoma, type 1': 'PRCC',
    'Papillary renal cell carcinoma, type 2': 'PRCC',
    'Renal cell carcinoma, not further classified': 'RCC, NOS',
    'Renal medullary carcinoma': 'RMC',
    'SDH deficient renal cell carcinoma': 'SDH RCC',
    'Tubulocystic renal cell carcinoma': 'TC RCC',
    'Unclassified RCC': 'Unclassified RCC',

}