#cloud-config
ssh_authorized_keys:
%(ssh_auth_keys)s
power_state:
  mode: poweroff
output:
  all: '| tee -a /var/log/cloud-init-output.log'
runcmd:
%(runcmd_all)s
%(runcmd_app)s
users:
%(users)s
write_files:
%(vimrc)s
%(env)s
%(upgrades)s
