#cloud-config
ssh_authorized_keys:
- %(ssh_key)s
apt_sources:
- source: "deb https://artifacts.elastic.co/packages/5.x/apt stable main"
- source: "deb http://apt.postgresql.org/pub/repos/apt/ bionic-pgdg main"
bootcmd:
- set -ex
- cloud-init-per once apt-update apt-get update
- cloud-init-per once fallocate-swapfile fallocate -l 4G /swapfile
- cloud-init-per once chmod-swapfile chmod 600 /swapfile
- cloud-init-per once mkswap-swapfile mkswap /swapfile
- cloud-init-per once aptkeyget-elasticsearch wget -qO - https://artifacts.elastic.co/GPG-KEY-elasticsearch > /etc/apt/es_gpg_key
- cloud-init-per once aptkeyadd-elasticsearch apt-key add /etc/apt/es_gpg_key
- cloud-init-per once aptkeyget-postgres wget -qO - https://www.postgresql.org/media/keys/ACCC4CF8.asc > /etc/apt/pg_gpg_key
- cloud-init-per once aptkeyadd-postgres apt-key add /etc/apt/pg_gpg_key
- cloud-init-per once curl-nodeinstall curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash -
packages:
# Additions for all builds
## General
- awscli
- git
- unattended-upgrades
## python
- build-essential
- libbz2-dev
- libdb-dev
- libffi-dev
- libgdbm-dev
- liblzma-dev
- libncurses5-dev
- libnss3-dev
- libreadline-dev
- libssl-dev
- libsqlite3-dev
- python3-dev
- python3-venv
- zlib1g-dev
## redis
- redis-server
# Additions for encoded application
## apache
- apache2
- apache2-dev
- apache2-utils
- debhelper
- dh-autoreconf
- ssl-cert
- libapache2-mod-wsgi-py3
- w3m
## ckeditor
- bsdtar
## Pillow
- libjpeg8-dev
- zlib1g-dev
## psycopg2
- libpq-dev
## postgresql
- daemontools
- postgresql-11
## node
- nodejs
### node optional installed for native add-ons
- g++
- gcc
- make
# snovault
## schema_graph -> https://linux.die.net/man/1/dot -> graphviz
- graphviz
# Other - Unknown
# - libevent-dev
# - libmagic-dev
# - libxml2-dev
# - libxslt1-dev
# Additions for elasticsearch
- apt-transport-https
- elasticsearch
# Additions for wal-e and postgres
- lzop
- pv
# Additions for node for encoded application
- nodejs
### node optional installed for native add-ons
- g++
- gcc
- make
power_state:
  mode: reboot
output:
  all: '| tee -a /var/log/cloud-init-output.log'
runcmd:
# AWS KEYS
- cloud-init-per once conf-encd-pem-s3 sudo -u ubuntu aws s3 cp --region=us-west-2 %(private_key_pem_src)s %(private_key_pem_dest)s
- cloud-init-per once conf-encd-pem-chmod sudo -u ubuntu chmod 0600 %(private_key_pem_dest)s
- cloud-init-per once conf-encd-cfg-s3 sudo -u ubuntu aws s3 cp --region=us-west-2 %(private_key_config_src)s %(private_key_config_dest)s
- cloud-init-per once conf-encd-cfg-chmod sudo -u ubuntu chmod 0600 %(private_key_config_dest)s
# Deployment Repo
- cloud-init-per once conf-git-repo sudo -u ubuntu git clone %(cnf_git_repo)s %(cnf_git_repo_dest)s
- cloud-init-per once conf-git-branch sudo -u ubuntu git -C %(cnf_git_repo_dest)s checkout -b %(cnf_git_branch)s  %(cnf_git_remote)s/%(cnf_git_branch)s
# System
- cloud-init-per once libmagic-mgc-install wget http://archive.ubuntu.com/ubuntu/pool/main/f/file/libmagic-mgc_5.38-4_amd64.deb && sudo dpkg -i libmagic-mgc_5.38-4_amd64.deb && sudo apt-get install -yf
- cloud-init-per once libmagic1-install wget http://archive.ubuntu.com/ubuntu/pool/main/f/file/libmagic1_5.38-4_amd64.deb && sudo dpkg -i libmagic1_5.38-4_amd64.deb && sudo apt-get install -yf
- cloud-init-per once libmagic-dev-install wget http://archive.ubuntu.com/ubuntu/pool/main/f/file/libmagic-dev_5.38-4_amd64.deb && sudo dpkg -i libmagic-dev_5.38-4_amd64.deb && sudo apt-get install -yf
- cloud-init-per once libmagic-dev-install sudo apt --fix-broken install && sudo apt autoremove
# Application
- cloud-init-per once encd-pre sudo -u ubuntu %(cc_dir)s/run-scripts/preapp.sh
- cloud-init-per always encd-app sudo -u ubuntu %(cc_dir)s/run-scripts/encoded.sh
# Monitoring
- cloud-init-per always encd-cloudwatch sudo -u ubuntu %(cc_dir)s/run-scripts/cloudwatchmon.sh
users:
- default
- name: build
  gecos: Build user
  inactive: true
  system: true
  shell: /bin/bash
- name: encoded
  gecos: ENCODE Metadata Database daemon user
  inactive: true
  system: true
  homedir: /srv/encoded
  shell: /bin/bash
write_files:
- path: /etc/vim/vimrc
  append: true
  content: |
    set number
    filetype plugin indent on
    set tabstop=4
    set shiftwidth=4
    set expandtab
- path: /etc/environment
  append: true
  content: |
    encd_app_workers=%(app_workers)s
    encd_batchupgrade=%(batchupgrade)s
    encd_batchupgrade_vars=%(batchupgrade_vars)s
    encd_build_type=%(build_type)s
    encd_cc_dir=%(cc_dir)s
    encd_es_ip=%(es_ip)s
    encd_es_jvm_gigs=%(es_jvm_gigs)s
    encd_es_opt_filename=%(es_opt_filename)s
    encd_es_port=%(es_port)s
    encd_fe_ip=%(fe_ip)s
    encd_git_branch=%(git_branch)s
    encd_git_commit=%(git_commit)s
    encd_git_remote=%(git_remote)s
    encd_git_repo=%(git_repo)s
    encd_home=%(home)s
    encd_index_primary=%(index_primary)s
    encd_index_vis=%(index_vis)s
    encd_index_region=%(index_region)s
    encd_index_procs=%(index_procs)s
    encd_index_chunk_size=%(index_chunk_size)s
    encd_install_tag=%(install_tag)s
    encd_pg_version=%(pg_version)s
    encd_pg_ip=%(pg_ip)s
    encd_pg_open=%(pg_open)s
    encd_py3_env=%(py3_env)s
    encd_remote_indexing=%(remote_indexing)s
    encd_role=%(role)s
    encd_pg_wale_s3_prefix=%(pg_wale_s3_prefix)s
- path: /etc/apt/apt.conf.d/20auto-upgrades
  content: |
    APT::Periodic::Update-Package-Lists "1";
    APT::Periodic::Unattended-Upgrade "1";
- path: /etc/apt/apt.conf.d/50unattended-upgrades
  content: |
    Unattended-Upgrade::Allowed-Origins {
        "${distro_id} ${distro_codename}-security";
    };
    Unattended-Upgrade::Mail "encode-devops@lists.stanford.edu";
    Unattended-Upgrade::Automatic-Reboot "false";
